### PR TITLE
Readme: Describe how to override Webpack config

### PR DESCRIPTION
**Pull request by goodwin64**
Solves https://github.com/SimonAlling/userscripter/issues/18

### CODE REVIEW

**Comment by SimonAlling** [comment]
Nice! I'll get back to you in a week or two; fairly busy atm.

**Comment by SimonAlling** [comment]
Hi again, @goodwin64! I've added a few suggestions. What do you think? :slightly_smiling_face:

**Comment by goodwin64** [comment]
Hi @SimonAlling!
Looks super!

**Comment by SimonAlling** [comment]
Thank you, @goodwin64!

**Pull request merged**
